export const data = [
    {
        question: "Qual a máquina virtual do Java?",
        a: "JVM",
        b: "Hardware",
        c: "VM",
        d: "Docker",
        correct: "a",
    },
    {
        question: "Qual comando Linux lista todos os diretórios e arquivos de uma pasta, incluindo os ocultos?",
        a: "ls -R",
        b: "ls -s",
        c: "ls -a",
        d: "ls -lh",
        correct: "c",
    },
    {
        question: "De qual linguagem o Java deriva?",
        a: "C#",
        b: "C++",
        c: "C",
        d: "Javascript",
        correct: "b",
    },
    {
        question: "Qual(is) comando(s) usamos para mostrar uma string na tela com php",
        a: "print e echo",
        b: "console.log",
        c: "printf",
        d: "System.out.println",
        correct: "a",
    },
    {
        question: "Para que serve o HTML semântico?",
        a: "print e echo",
        b: "console.log",
        c: "printf",
        d: "System.out.println",
        correct: "a",
    },
];
